language: node_js
node_js:
  - 6
  - 7
  - 8
script:
  - npm run build-css
  - npm run lint
  - npm test -- --no-watch --coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
